/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAboutRouteImport } from './routes/dashboard/about'
import { Route as DashboardCompetitionsRouteImport } from './routes/dashboard/competitions'
import { Route as DashboardMatchesRouteImport } from './routes/dashboard/matches'
import { Route as DashboardNewsRouteImport } from './routes/dashboard/news'
import { Route as DashboardPlayersRouteImport } from './routes/dashboard/players'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard/predictions'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitionsRoute = DashboardCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchesRoute = DashboardMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayersRoute = DashboardPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/mcp'
    | '/dashboard/about'
    | '/dashboard/competitions'
    | '/dashboard/matches'
    | '/dashboard/news'
    | '/dashboard/players'
    | '/dashboard/predictions'
    | '/dashboard/teams'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/about/'
    | '/dashboard/'
    | '/login/'
    | '/signup/'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/dashboard/about'
    | '/dashboard/competitions'
    | '/dashboard/matches'
    | '/dashboard/news'
    | '/dashboard/players'
    | '/dashboard/predictions'
    | '/dashboard/teams'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/mcp'
    | '/dashboard/about'
    | '/dashboard/competitions'
    | '/dashboard/matches'
    | '/dashboard/news'
    | '/dashboard/players'
    | '/dashboard/predictions'
    | '/dashboard/teams'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/about/'
    | '/dashboard/'
    | '/login/'
    | '/signup/'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitions': {
      id: '/dashboard/competitions'
      path: '/competitions'
      fullPath: '/dashboard/competitions'
      preLoaderRoute: typeof DashboardCompetitionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matches': {
      id: '/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof DashboardMatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/players': {
      id: '/dashboard/players'
      path: '/players'
      fullPath: '/dashboard/players'
      preLoaderRoute: typeof DashboardPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardCompetitionsRoute: typeof DashboardCompetitionsRoute
  DashboardMatchesRoute: typeof DashboardMatchesRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardPlayersRoute: typeof DashboardPlayersRoute
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardCompetitionsRoute: DashboardCompetitionsRoute,
  DashboardMatchesRoute: DashboardMatchesRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardPlayersRoute: DashboardPlayersRoute,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
